name: system_status_plugin
description: "A Flutter plugin to get system info like model, board, manufacturer, and screen size."
version: 0.0.1
homepage: https://github.com/Rahul675/system_status_plugin
repository: https://github.com/Rahul675/system_status_plugin
issue_tracker: https://github.com/Rahul675/system_status_plugin/issues

environment:
  sdk: ^3.5.4
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tomertech.system_status_plugin
        pluginClass: SystemStatusPlugin
